[package]
name = "lambdaworks-stark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
lambdaworks-math = { path = "../../math" }
lambdaworks-crypto = { path = "../../crypto" }
lambdaworks-fft = { path = "../../fft" }
thiserror = "1.0.38"
embedded-hal = { version = "1.0.0-alpha.9", optional = true }
esp-idf-sys = { version = "0.32", features = ["binstart"], optional = true }
esp-idf-hal = { version = "0.40.1", optional = true }

[dev-dependencies]
hex = "0.4.3"
criterion = "0.4"

[build-dependencies]
embuild = "0.31.1"
anyhow = "1"

[features]
test_fiat_shamir = []
esp = [
    "embedded-hal",
    "esp-idf-sys",
    "esp-idf-hal",
    "lambdaworks-math/esp",
    "lambdaworks-crypto/esp",
    "lambdaworks-fft/esp"
]

[[bench]]
name = "all_benchmarks"
harness = false

[[bench]]
name = "stark_benchmarks"
harness = false
