[package]
name = "lambdaworks-gpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metal = "0.24.0"
lambdaworks-math = { path = "../math" }
lambdaworks-crypto = { path = "../crypto"}
proptest = "1.1.0"
