[workspace]
default-members = [
    "math",
    "crypto",
    "proving_system/stark",
    "proving_system/plonk",
    "py"
]
members = [
    "math",
    "crypto",
    "proving_system/stark",
    "proving_system/plonk",
    "gpu",
    "py"
]
