[package]
name = "lambdaworks-math"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
thiserror = "1.0.38"
embedded-hal = { version = "1.0.0-alpha.9", optional = true }
esp-idf-sys = { version = "0.32", features = ["binstart"], optional = true }
esp-idf-hal = { version = "0.40.1", optional = true }

[dev-dependencies]
proptest = "1.1.0"
criterion = "0.4"
const-random = "0.1.15"

[build-dependencies]
embuild = "0.31.1"
anyhow = "1"

[[bench]]
name = "all_benchmarks"
harness = false

[[bench]]
name = "field_benchmarks"
harness = false

[[bench]]
name = "polynomial_benchmarks"
harness = false

[features]
pio = ["esp-idf-sys/pio"]
esp = ["embedded-hal", "esp-idf-sys", "esp-idf-hal"]
