[package]
name = "winterfell_adapter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
lambdaworks-math = { path = "../math", features=["winter_compatibility"] }
stark-platinum-prover = { path = "../provers/stark" , features=["winter_compatibility"]}
rand = "0.8.5"

winter-air = { git = "https://github.com/lambdaclass/winterfell-for-lambdaworks", revision="c1bdc2d", default-features = false }
winter-prover ={ git = "https://github.com/lambdaclass/winterfell-for-lambdaworks", revision="c1bdc2d", default-features = false } 
winter-math ={ git = "https://github.com/lambdaclass/winterfell-for-lambdaworks", revision="c1bdc2d", default-features = false } 
winter-utils ={ git = "https://github.com/lambdaclass/winterfell-for-lambdaworks", revision="c1bdc2d", default-features = false } 
miden-air = { git="https://github.com/lambdaclass/miden-vm/" }
miden-core = { git="https://github.com/lambdaclass/miden-vm/" }
miden-assembly = { git="https://github.com/lambdaclass/miden-vm/" }
miden-processor = { git="https://github.com/lambdaclass/miden-vm/" }
sha3 = "0.10"
 
[dev-dependencies]
criterion = { version = "0.4", default-features = false }
miden-prover = { git="https://github.com/lambdaclass/miden-vm/" }

[[bench]]
name = "proving"
harness = false
