[package]
name = "lambdaworks-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.10.6"
sha2 = { version = "0.10.6", optional = true }
embedded-hal = { version = "1.0.0-alpha.9", optional = true }
esp-idf-sys = { version = "0.32", features = ["binstart"], optional = true }
esp-idf-hal = { version = "0.40.1", optional = true }

[dependencies.lambdaworks-math]
path = "../math"

[dependencies.rand]
version = "0.8"

[build-dependencies]
embuild = "0.31.1"
anyhow = "1"

[features]
test_fiat_shamir = []
esp = ["sha2", "embedded-hal", "esp-idf-sys", "esp-idf-hal", "lambdaworks-math/esp"]
